config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('medical_services.urls'))
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medical_services/urls.py
from django.urls import path
from medical_services.views import home, CategoryListView, CategoryCreateView, ServiceListView, \
    CategoryServiceListView, \
    ServiceCreateView, ServiceDetailView, ServiceUpdateView, ServiceDeleteView, CategoryUpdateView, \
    CategoryDeleteView, ContactView, ServiceCartView, AddToCartView, remove_service, clear_service

app_name = 'medical_services'

urlpatterns = [
    path('', home, name='home'),
    path('contacts/', ContactView.as_view(), name='contacts'),
    path('service_cart/', ServiceCartView.as_view(), name='service_cart'),

    path('category_create/', CategoryCreateView.as_view(), name='category_create'),
    path('category_list/', CategoryListView.as_view(), name='category_list'),
    path('category_update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category_delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

    path('service_create/', ServiceCreateView.as_view(), name='service_create'),
    path('service_list/', ServiceListView.as_view(), name='service_list'),
    path('service_list/<int:pk>/', CategoryServiceListView.as_view(), name='service_list'),
    path('service_detail/<int:pk>/', ServiceDetailView.as_view(), name='service_detail'),
    path('service_update/<int:pk>/', ServiceUpdateView.as_view(), name='service_update'),
    path('service_delete/<int:pk>/', ServiceDeleteView.as_view(), name='service_delete'),
    path('add_to_cart/<int:pk>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove_service/<int:service_id>/', remove_service, name='remove_service'),
    path('clear_service/', clear_service, name='clear_service'),
    ]

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import LoginView, logout_view, RegisterView, ProfileView, generate_new_password, \
    confirm_registration, invalid_token_view, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword', generate_new_password, name='generate_new_password'),
    path('confirm-registration/<str:token>/', confirm_registration, name='confirm_registration'),
    path('invalid-token/', invalid_token_view, name='invalid_token'),
    path('password-reset/', reset_password, name='reset_password'),
]

medical_services/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    """ Категории услуг """
    category_title = models.CharField(max_length=100, verbose_name='название')
    category_description = models.TextField(verbose_name='описание')
    category_image = models.ImageField(upload_to='categories/', verbose_name='изображение', **NULLABLE)

    def __str__(self):
        return self.category_title

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"


class Service(models.Model):
    """ Услуги """
    services_title = models.CharField(max_length=100, verbose_name='название')
    services_description = models.TextField(verbose_name='описание')
    services_image = models.ImageField(upload_to='services/', verbose_name='изображение', **NULLABLE)
    price = models.PositiveIntegerField(verbose_name='цена')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    deadline = models.CharField(max_length=100, verbose_name='срок выполнения')

    def __str__(self):
        return self.services_title

    class Meta:
        verbose_name = "услуга"
        verbose_name_plural = "услуги"


class Cart(models.Model):
    """ Корзина """
    client = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='клиент')
    services = models.ManyToManyField('Service', verbose_name='услуги')
    date = models.DateTimeField(verbose_name='дата и время', **NULLABLE)

    def __str__(self):
        return f'{self.client} - {self.services}'

    class Meta:
        verbose_name = "корзина"
        verbose_name_plural = "корзины"

medical_services/forms.py
from django import forms
from medical_services.models import Service, Category


class CategoryForm(forms.ModelForm):
    """ Формы для взаимодействия с моделями категорий """
    class Meta:
        model = Category
        fields = ("category_title", "category_description", "category_image",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ServicesForm(forms.ModelForm):
    """ Формы для взаимодействия с моделями услуг """
    class Meta:
        model = Service
        fields = ("services_title", "services_description", "category", "price", "deadline",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

medical_services/views.py
import json
from django.conf import settings
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.mail import send_mail
from django.http import HttpResponseForbidden, JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.views import View
from django.views.generic import ListView, DeleteView, DetailView, CreateView, UpdateView
from medical_services.forms import CategoryForm, ServicesForm
from medical_services.models import Category, Service, Cart
from django.urls import reverse_lazy, reverse


def home(request):
    """ Главная страница сайта """
    return render(request, 'medical_services/home.html')


# Классы категории
class CategoryCreateView(CreateView, PermissionRequiredMixin):
    """ Добавление категории """
    model = Category
    form_class = CategoryForm
    permission_required = 'medical_services.add_category'
    success_url = reverse_lazy("medical_services:category_list")

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    def dispatch(self, request, *args, **kwargs):
        """ Проверка на доступ к добавлению категории """
        if not request.user.has_perm('medical_services.add_category'):
            return HttpResponseForbidden("У вас нет доступа")
        return super().dispatch(request, *args, **kwargs)


class CategoryListView(ListView):
    """ Список категорий """
    model = Category


class CategoryUpdateView(UpdateView, PermissionRequiredMixin):
    """ Редактирование категории """
    model = Category
    form_class = CategoryForm
    permission_required = 'medical_services.change_category'
    success_url = reverse_lazy("medical_services:category_list")

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    def dispatch(self, request, *args, **kwargs):
        """ Проверка на доступ к редактированию категории """
        if not request.user.has_perm('medical_services.change_category'):
            return HttpResponseForbidden("У вас нет доступа")
        return super().dispatch(request, *args, **kwargs)


class CategoryDeleteView(DeleteView, PermissionRequiredMixin):
    """ Удаление категории """
    model = Category
    success_url = reverse_lazy("medical_services:category_list")
    permission_required = 'medical_services.delete_category'
    template_name = "medical_services/category_confirm_delete.html"

    def get_context_data(self, **kwargs):
        """ Добавление списка услуг к категории """
        context = super().get_context_data(**kwargs)
        context['object_list'] = self.get_object().category_title
        return context

    def dispatch(self, request, *args, **kwargs):
        """ Проверка на доступ к удалению категории """
        if not request.user.has_perm('medical_services.delete_category'):
            return HttpResponseForbidden("У вас нет доступа")
        return super().dispatch(request, *args, **kwargs)


class CategoryServiceListView(ListView):
    """ Список услуг к категории """
    model = Service

    def get_queryset(self):
        """ Фильтрация услуг по категории """
        category_pk = self.kwargs['pk']
        return Service.objects.filter(category_id=category_pk)


# Классы услуг
class ServiceCreateView(CreateView, PermissionRequiredMixin):
    """ Добавление услуги """
    model = Service
    form_class = ServicesForm
    permission_required = 'medical_services.add_service'
    success_url = reverse_lazy("medical_services:service_list")

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    def dispatch(self, request, *args, **kwargs):
        """ Проверка на доступ к добавлению услуги """
        if not request.user.has_perm('medical_services.add_service'):
            return HttpResponseForbidden("У вас нет доступа")
        return super().dispatch(request, *args, **kwargs)


class ServiceListView(ListView):
    """ Список услуг """
    model = Service


class ServiceDetailView(DetailView):
    """ Подробная информация о услуге """
    model = Service

    def get(self, request, pk):
        """ Подробная информация о услуге """
        product = Service.objects.get(pk=pk)
        context = {
            'object_list': Service.objects.filter(id=pk),
        }
        return render(request, 'medical_services/service_detail.html', context)


class ServiceUpdateView(UpdateView, PermissionRequiredMixin):
    """ Редактирование услуги """
    model = Service
    form_class = ServicesForm
    permission_required = 'medical_services.change_service'
    success_url = reverse_lazy("medical_services:service_list")

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    def dispatch(self, request, *args, **kwargs):
        """ Проверка на доступ к редактированию услуги """
        if not request.user.has_perm('medical_services.change_service'):
            return HttpResponseForbidden("У вас нет доступа")
        return super().dispatch(request, *args, **kwargs)


class ServiceDeleteView(DeleteView, PermissionRequiredMixin):
    """ Удаление услуги """
    model = Service
    success_url = reverse_lazy("medical_services:service_list")
    permission_required = 'medical_services.delete_service'
    template_name = "medical_services/service_confirm_delete.html"

    def get_context_data(self, **kwargs):
        """ Добавление списка услуг к категории """
        context = super().get_context_data(**kwargs)
        context['object_list'] = self.get_object().services_title
        return context

    def dispatch(self, request, *args, **kwargs):
        """ Проверка на доступ к удалению услуги """
        if not request.user.has_perm('medical_services.delete_service'):
            return HttpResponseForbidden("У вас нет доступа")
        return super().dispatch(request, *args, **kwargs)


def remove_service(request, service_id):
    """ Удаление услуги из корзины """
    if request.method == 'POST':
        service = get_object_or_404(Service, id=service_id)
        cart = Cart.objects.get(client=request.user)
        cart.services.remove(service)
        return redirect(reverse('medical_services:service_cart'))
    else:
        return redirect(reverse('medical_services:service_cart'))


def clear_service(request):
    """ Очистка корзины """
    if request.method == 'POST':
        cart = Cart.objects.get(client=request.user)
        cart.services.clear()
        return redirect(reverse('medical_services:service_cart'))
    else:
        return redirect(reverse('medical_services:service_cart'))


class ContactView(View):
    """ Контакты """

    def get(self, request):
        return render(request, 'medical_services/contacts.html')

    def post(self, request):
        if request.method == 'POST':
            name = request.POST.get('name')
            phone = request.POST.get('phone')
            message = request.POST.get('message')

            # Логика для отправки письма администратору
            subject = 'Обращение от посетителя сайта'
            admin_message = f'Имя: {name}\nТелефон: {phone}\nСообщение: {message}'
            send_mail(
                subject=subject,
                message=admin_message,
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[settings.EMAIL_HOST_USER],  # Замените на реальный адрес администратора
            )

            success_message = 'Ваше сообщение успешно отправлено. Мы свяжемся с вами в ближайшее время.'
            context = {'success_message': success_message}
            return render(request, 'medical_services/contacts_success.html', context)


class ServiceCartView(View):
    """ Корзина """
    model = Cart

    def get(self, request):
        # Получаем объект корзины для текущего пользователя
        cart = Cart.objects.filter(client=request.user).first()

        # Получаем количество услуг в корзине
        services_count = cart.services.count() if cart else 0

        # Получаем список услуг в корзине
        services = cart.services.all() if cart else []

        # Получаем данные о клиенте
        client = cart.client if cart else None

        # Получаем сумму покупок услуг в корзине
        total_price = sum(service.price for service in services)

        # Обновляем контекст
        context = {
            'services_count': services_count,
            'services': services,
            'total_price': total_price,
            'client': client
        }
        return render(request, 'medical_services/shopping_cart.html', context)

    def post(self, request):
        """ Отправка письма администратору и пользователю """
        cart = Cart.objects.filter(client=request.user).first()
        if cart:
            services = cart.services.all()
            total_price = sum(service.price for service in services)

            # Логика для отправки письма администратору
            context = {'services': services, 'total_price': total_price, 'user': request.user}
            admin_message = render_to_string('medical_services/admin_cart_email.html', context)
            send_mail(
                subject='Новый заказ в медицинской клинике',
                message='Новый заказ в медицинской клинике',
                html_message=admin_message,
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[settings.EMAIL_HOST_USER],
            )

            # Логика для отправки письма пользователю
            user_message = render_to_string('medical_services/cart_email.html', context)
            send_mail(
                subject='Оформление заказа в медицинской клинике',
                message='Оформление заказа в медицинской клинике',
                html_message=user_message,
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[request.user.email],
            )

medical_services/templates/medical_services/admin_cart_email.html
<h2>Новый заказ на сайте</h2>
<p>Пользователь {{ user.email }} оформил заказ на сумму {{ total_price }} рублей.</p>
<ul>
    {% for service in services %}
        <li>{{ service.services_title }} - {{ service.price }} ₽</li>
    {% endfor %}
</ul>

medical_services/templates/medical_services/category_confirm_delete.html
{% extends 'medical_services/base.html' %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить продукт "{{ object.category_title }}"?</p>
                    <button type="submit" class="btn btn-success">Подтвердить</button>
                    <a href="{% url 'medical_services:service_list' %}" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

medical_services/templates/medical_services/category_list.html
{% extends 'medical_services/base.html' %}
{% load my_tags_medical_services %}
{% block content %}
<style>
    .details-summary {
        list-style: none;
        cursor: pointer;
        background-color: #fff;
        color: #000;
        padding: 8px 16px;
        border: 1px solid #ffffff;
        border-radius: 4px;
        display: inline-block;
        transition: background-color 0.3s, color 0.3s;
        margin-bottom: 5px;
    }

    .details-summary:hover {
        background-color: #ffffff;
        border-color: #666666;
    }

    .details-summary:focus {
        outline: none;
    }
</style>
<div class="col-12 mb-5">
    {% if user.is_staff or user.is_superuser %}
    <a class="btn btn-info" href="{% url 'medical_services:category_create' %}">Добавить категорию</a>
    {% endif %}
</div>
{% for object in object_list %}
<div class="col-md-6">
    <div class="card mb-4 box-shadow">
        <details>
        <summary class="details-summary">
                <img class="card-img-top"
                     src="{{ object.category_image | category_image }}" width="300" height="225"
                     alt="Card image cap">
                <b>Категория:</b> {{ object.category_title | slice:":100" }}

            </summary>
        <div class="card-body">
            <p class="card-text">
                <b>Описание:</b> {{ object.category_description | slice:":100" }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <form>
                        <a href="{% url 'medical_services:service_list' pk=object.id %}" class="btn btn-sm btn-info">Посмотреть</a>
                        {% if user.is_staff or user.is_superuser %}
                        <a href="{% url 'medical_services:category_update' object.pk %}" class="btn btn-sm btn-info">Изменить</a>
                        <a href="{% url 'medical_services:category_delete' object.pk %}" class="btn btn-sm btn-danger">Удалить</a>
                        {% endif %}
                    </form>
                </div>
                <small class="text-muted"></small>
            </div>
        </div>
        </details>
    </div>
</div>
{% endfor %}
{%  endblock %}

medical_services/templates/medical_services/contacts_success.html
{% extends "medical_services/base.html" %}

{% block content %}
<div class="container">
    <div class="py-5 text-center">
        <h2>Успех!</h2>
        <p>{{ success_message }}</p>
        <a href="{% url 'medical_services:home' %}" class="btn btn-primary">Вернуться на главную</a>
    </div>
</div>
{% endblock %}

medical_services/templates/medical_services/menu.html
{% load static %}

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white" style="text-align: center;">Центр медицинских анализов</h4>
                    <div class="col-12 d-flex justify-content-start align-items-center">
                        <a class="nav-link d-flex align-items-center text-light mx-2"
                           href="{% url 'medical_services:home' %}"><u>Главная</u></a>
                        <a class="nav-link d-flex align-items-center text-light mx-2"
                           href="{% url 'medical_services:category_list' %}"><u>Категории</u></a>
                        <a class="nav-link d-flex align-items-center text-light mx-2"
                           href="{% url 'medical_services:service_list' %}"><u>Услуги</u></a>
                        <a class="nav-link d-flex align-items-center text-light mx-2"
                           href="{% url 'medical_services:contacts' %}"><u>Контакты</u></a>
                        {% if user.is_authenticated %}
                        <a class="nav-link d-flex align-items-center text-light mx-2"
                           href="{% url 'medical_services:service_cart' %}"><u>Корзина</u></a>
                        {% endif %}
                        {% if user.is_superuser or user.is_staff %}
                        <a class="nav-link d-flex align-items-center text-light mx-2"
                           href="/admin/"><u>Админка</u></a>
                        {% endif %}
                    </div>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    {% if user.is_authenticated %}
                    {% if user.first_name %}
                    <h4 class="text-light">Пользователь: {{ user.first_name }} {{ user.last_name }}</h4>
                    {% else %}
                    <h4 class="text-light">Пользователь: {{ user.email }}</h4>
                    {% endif %}
                    <div class="col-12 d-flex flex-column justify-content-end align-items-end">
                        <!--                        <div class="col-12  justify-content-start align-items-center">&ndash;&gt;-->
                        <a class="nav-link d-flex align-items-center text-light mx-2"
                           href="{% url 'users:profile' %}"><u>Профиль</u></a>
                        <a class="nav-link d-flex align-items-center text-danger mx-2"
                           href="{% url 'users:logout' %}"><u>Выход</u></a>
                    </div>
                    {% else %}
                    <h4 class="text-muted">Войдите в личный кабинет</h4>
                    <div class="col-12  justify-content-start align-items-center">
                        <a class="nav-link d-flex align-items-center text-light mx-2"
                           href="{% url 'users:login' %}"><u>Вход</u></a>
                        <a class="nav-link d-flex align-items-center text-light mx-2"
                           href="{% url 'users:register' %}"><u>Регистрация</u></a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
            <a href="{% url 'medical_services:home' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2"
                     viewBox="0 0 24 24" focusable="false">
                    <img src="{% static 'logo.png' %}" width="100" height="93" alt="Logo"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

medical_services/templates/medical_services/service_list.html
{% extends 'medical_services/base.html' %}
{% load my_tags_medical_services %}
{% block content %}
<style>
    .card-body {
        overflow: hidden;
    }

    .card-text {
        overflow: hidden;
        max-height: 30px;
        transition: max-height 0.5s;
    }

    .card-body:hover .card-text {
        max-height: 200px;
        transition: max-height 0.5s;
    }
    .no-border-radius {
    border-top-left-radius: 0;
    border-top-right-radius: 0;
    }
</style>

<div class="col-12 mb-5">
    {% if user.is_staff or user.is_superuser %}
    <a class="btn btn-sm btn-info" href="{% url 'medical_services:service_create' %}">Добавить услугу</a>
    {% endif %}
</div>
{% for object in object_list %}
<div class="col-md-12">
    <div class="card mb-4 box-shadow">
        <div class="card-body">

            <p class="card-text">
                <b>Название:</b> {{ object.services_title | slice:":100" }}
            </p>
            <div class="card-text">
                <p class="card-text">
                    <b>Категория:</b> {{ object.category | slice:":100" }}
                </p>
                <p>
                    <b>Описание:</b> {{ object.services_description | slice:":100" }}
                </p>
                <p>
                    <b>Цена:</b> {{ object.price | slice:":100" }} рублей
                </p>
                <p>
                    <b>Срок выполнения:</b> {{ object.deadline| slice:":100" }}
                </p>
            </div>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <form>

                        <a href="{% url 'medical_services:service_detail' object.pk %}" class="btn btn-sm btn-info">Посмотреть</a>

                        {% if user.is_staff or user.is_superuser %}
                        <a href="{% url 'medical_services:service_update' object.pk %}" class="btn btn-sm btn-info">Изменить</a>
                        <a href="{% url 'medical_services:service_delete' object.pk %}" class="btn btn-sm btn-danger">Удалить</a>
                        {% endif %}
                    </form>
                </div>
                <small class="text-muted"></small>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

medical_services/templates/medical_services/shopping_cart.html
{% extends 'medical_services/base.html' %}

{% block content %}

<div class="container">
    <div class="py-5 text-center">
        <h2>Корзина</h2>
        <p class="lead">Проверьте ваш заказ услуг.<br>После нажатия кнопки "Записаться" вам на почту придет письмо с
            указанием выбранных вами услуг.<br>После отправки в ближайшее время с вами свяжется администратор
            для назначения времени приема.</p>
    </div>

    <div class="row">
        <div class="col-md-7 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="mb-3">Ваш заказ</span>
                <span class="badge badge-secondary badge-pill">{{ services_count }}</span>
            </h4>

            <ul class="list-group mb-3">
                {% for service in services %}
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">{{ service.services_title | slice:":50" }}</h6>
                        <small class="text-muted">Срок выполнения: {{ service.deadline }}</small>
                    </div>
                    <span class="text-muted">{{ service.price }} ₽</span>
                    <form method="post" action="{% url 'medical_services:remove_service' service.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="service_id" value="{{ service.id }}">
                        <button type="submit" class="btn btn-link text-danger">
                            <img src="/media/image.png" alt="корзина" width="20" height="20"/>
                        </button>
                    </form>
                </li>
                {% endfor %}
                <li class="list-group-item d-flex justify-content-between">
                    <span><strong>Итого</strong></span>
                    <strong>{{ total_price }} ₽</strong>
                </li>
            </ul>
            <form method="post" action="{% url 'medical_services:clear_service' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Очистить</button>
            </form>
        </div>
        <div class="col-md-5 order-md-1">
            <h4 class="mb-3">Данные клиента</h4>
            <form class="needs-validation" novalidate>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="firstName">Имя</label>
                        <input type="text" class="form-control" id="firstName"
                               placeholder="{% if client.first_name %}{{ client.first_name }}{% endif %}"
                               value="{% if client.first_name %}{{ client.first_name }}{% endif %}" required>
                        <div class="invalid-feedback">
                            Valid first name is required.
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="lastName">Фамилия</label>
                        <input type="text" class="form-control" id="lastName" placeholder=""
                               value="{% if client.last_name %}{{ client.last_name }}{% endif %}" required>
                        <div class="invalid-feedback">
                            Valid last name is required.
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="lastName">Отчество(при наличии)</label>
                        <input type="text" class="form-control" id="patronymic" placeholder=""
                               value="{% if client.patronymic %}{{ client.patronymic }}{% endif %}" required>
                        <div class="invalid-feedback">
                            Valid patronymic is required.
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="lastName">Номер телефона</label>
                        <input type="text" class="form-control" id="phone" placeholder=""
                               value="{% if client.phone %}{{ client.phone }}{% endif %}" required>
                        <div class="invalid-feedback">
                            Valid phone is required.
                        </div>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="email">Email</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">@</span>
                        </div>
                        <input type="text" class="form-control" id="email" placeholder=""
                               value="{% if client.email %}{{ client.email }}{% endif %}" required>
                        <div class="invalid-feedback" style="width: 100%;">
                            Your username is required.
                        </div>
                    </div>
                </div>
                <hr class="mb-4">

            </form>
            <form method="post">
                {% csrf_token %}
                <button class="btn btn-primary btn-lg btn-block" type="submit">Записаться</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}